### PR TITLE
allow use of d3 v4.x

### PR DESCRIPTION
**Pull request by bradoyler**
- add example and tests

cc: @petulla

### CODE REVIEW

**Comment by petulla** [comment]
One thing to note. Only difference with V4 I can see is the d3 scale generator.

In 3.X:

d3.scale.linear()

in 4.x

d3.scaleLinear()

You could parameterize with

d3['scaleLinear']() vs. d3['scale']['linear']()

**Comment by bradoyler** [comment]
Not sure what u mean, everything has changed. 
https://github.com/d3/d3/blob/master/CHANGES.md

**Comment by petulla** [comment]
Oh yeah, true :/ Just saying for the line chart demo.

**Comment by bradoyler** [comment]
@petulla added example of a Voronoi diagram
screen shot 2016-08-14 at 4 19 06 pm
💃

**Comment by petulla** [comment]
Awesome. Really useful for UIs: https://youtu.be/90NsjKvz9Ns?t=13m17s

**Pull request merged**
